[package]
name = "font-atlas"
version = "0.1.0"
authors = ["Michael Zoech <michi.zoech@gmail.com>"]

[dependencies]
cairo-rs = "0.3"
freetype-rs = "0.16"
gdk = "0.7"

[dependencies.gtk]
version = "0.3"
features = ["v3_20"]
