[package]
name = "font-atlas"
version = "0.1.0"
authors = ["Michael Zoech <michi.zoech@gmail.com>"]

[dependencies]
cairo-rs = { version = "0.3", features = ["png"] }
freetype-rs = "0.17"
gdk = "0.7"
glib = "0.4.1"

[dependencies.gtk]
version = "0.3"
features = ["v3_20"]
